env:
            - name: NODE_ENV
              value: "{{ .Values.backend.env.NODE_ENV }}"
            - name: PORT
              value: "{{ .Values.backend.env.PORT }}"
            # આ લાઇનો સીધી કુબરનેટિસ સિક્રેટમાંથી ડેટા લોડ કરશે
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: eventora-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eventora-secrets
                  key: JWT_SECRET
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: eventora-secrets
                  key: EMAIL_USER
            - name: EMAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: eventora-secrets
                  key: EMAIL_PASS




                  