apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventora-backend
  labels:
    app: eventora-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: eventora-backend
  template:
    metadata:
      labels:
        app: eventora-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.repository }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: NODE_ENV
              value: "{{ .Values.backend.env.NODE_ENV }}"
            - name: PORT
              value: "{{ .Values.backend.env.PORT }}"
            - name: MONGO_URI
              value: "{{ .Values.backend.env.MONGO_URI }}"
            - name: JWT_SECRET:
              value: "{{ .Values.backend.env.JWT_SECRET }}"