apiVersion: v1
kind: Service
metadata:
  name: eventora-frontend-svc
spec:
  type: ClusterIP # ઇન્ગ્રેસ હોવાથી આને ઇન્ટર્નલ આઇપી (ClusterIP) જ રખાય
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.containerPort }}
      protocol: TCP
  selector:
    app: eventora-frontend